name: news-article CI
on:
    push: 
        branches: 
            - main
            - develop
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
             - name: Checkout source code
               uses: actions/checkout@v4
             - name: Setup .NET
               uses: actions/setup-dotnet@v4
               with:
                 dotnet-version: '10.0.x'
             - name: Restore
               run: dotnet restore

             - name: Build
               run: dotnet build --no-restore --configuration Release
             - name: Publish
               run: dotnet publish --configuration Release --output ./publish
             - name: Upload artifact
               uses: actions/upload-artifact@v4
               with:
                  name: news-article-api
                  path: ./publish


